apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-argocd
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: quyetjs/lab_argocd:v1.0.2
        ports:
        - containerPort: 8080
